version: '3.8'

services:
  spark-jupyter:
    build: .
    container_name: spark-jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
      - "5000:5000"
    volumes:
      - ./notebooks:/home/jovyan/work