services:
  spark-jupyter:
    build: .
    container_name: spark-jupyter
    env_file:
      - .env         # Variables locales, NO subir a git
    ports:
      - "8888:8888"  # JupyterLab
      - "4040:4040"  # Spark UI
      - "5000:5000"  # MLflow
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./platzi:/home/jovyan/workspace
      - ./state:/home/jovyan/state        # backend SQLite persistente
      - ./mlruns:/home/jovyan/mlruns      # artifacts persistentes

    command: ["bash", "/home/jovyan/start-with-mlflow.sh"]
